@startuml
actor Comprador
boundary "Interfície Comanda"
control "Gestor Comanda"
entity Comanda
entity Plat

' --- AFEGIR PLAT ---
Comprador -> "Interfície Comanda" : AfegirPlat()
activate "Interfície Comanda"

"Interfície Comanda" -> "Gestor Comanda" : AfegirPlat()
activate "Gestor Comanda"

"Gestor Comanda" -> Plat : BuscarPlat()
activate Plat
Plat --> "Gestor Comanda" : return()
deactivate Plat

"Gestor Comanda" -> Comanda : AfegirCarret()
activate Comanda
Comanda --> "Gestor Comanda" : return()
deactivate Comanda

' --- ACCEDIR CARRET ---
Comprador -> "Interfície Comanda" : AccedirCarret()

"Interfície Comanda" -> "Gestor Comanda" : AccedirCarret()

"Gestor Comanda" -> Comanda : BuscarCarret()
activate Comanda
Comanda --> "Gestor Comanda" : Return
deactivate Comanda

"Gestor Comanda" --> "Interfície Comanda" : MostrarCarret()

' --- MODIFICAR INGREDIENTS ---
Comprador -> "Interfície Comanda" : ModIngred()

"Interfície Comanda" -> "Gestor Comanda" : ModIngred()

"Gestor Comanda" -> Comanda : ModIngredPlat()

' --- A1: CANCEL·LACIÓ ---
opt A1 (Si client surt)
    Comprador -> "Interfície Comanda" : Sortir()
end

' --- A2: ERROR INGREDIENTS ---
opt A2 (Si el Plat no té ingredients opcionals)
    "Gestor Comanda" --> "Interfície Comanda" : Error_NO_Ing()
end

deactivate Plat
deactivate "Gestor Comanda"
deactivate "Interfície Comanda"

@enduml
