@startuml
actor Comprador
boundary "Interfície Comandes"
control "Gestor Comandes"
control "Gestor Maps"
control "Gestor Pagament"
entity Comanda
entity DadesComprador

' --- 1, 2 i 3. INICI I CÀLCUL DE PREU AMB GOOGLE MAPS ---
Comprador -> "Interfície Comandes" : ContinuarPagament()
activate "Interfície Comandes"

"Interfície Comandes" -> "Gestor Comandes" : CalcularPreuFinal()
activate "Gestor Comandes"

"Gestor Comandes" -> Comanda : obtenirDetalls()
activate Comanda
Comanda --> "Gestor Comandes" : dades (productes, adreces)
deactivate Comanda

' Càlcul de distància delegat al nou gestor
"Gestor Comandes" -> "Gestor Maps" : calcularDistancia(origen, desti)
activate "Gestor Maps"
"Gestor Maps" --> "Gestor Comandes" : distancia (km)
deactivate "Gestor Maps"

' --- S2. PUNTS DE SUBSCRIPCIÓ ---
opt S2 (Punts de subscripció)
    "Gestor Comandes" -> DadesComprador : consultarPunts()
    activate DadesComprador
    DadesComprador --> "Gestor Comandes" : puntsAcumulats
    deactivate DadesComprador
end

"Gestor Comandes" -> Comanda : calcularPreuTotal(distancia)
activate Comanda
Comanda --> "Gestor Comandes" : preuFinal
deactivate Comanda

"Gestor Comandes" --> "Interfície Comandes" : MostrarPreuFinal(preuFinal)
deactivate "Gestor Comandes"

' --- 4 i 5. PROCÉS DE PAGAMENT AMB GESTOR BANCARI ---
Comprador -> "Interfície Comandes" : PagarComanda()

"Interfície Comandes" -> "Gestor Comandes" : ProcessarPagament()
activate "Gestor Comandes"

"Gestor Comandes" -> "Gestor Pagament" : AutenticarPagament(import)
activate "Gestor Pagament"

' --- A1. ERROR EN EL PAGAMENT ---
alt A1 (Error en el pagament)
    "Gestor Pagament" --> "Gestor Comandes" : TransaccioDenegada()
    "Gestor Comandes" --> "Interfície Comandes" : ErrorPagament()
    "Interfície Comandes" --> Comprador : MostrarMissatgeError()
else Pagament Correcte
    "Gestor Pagament" --> "Gestor Comandes" : TransaccioExitosa()
    deactivate "Gestor Pagament"

    ' --- 6. CONFIRMACIÓ I FACTURA ---
    "Gestor Comandes" -> Comanda : actulitzarEstat(PAGADA)
    activate Comanda
    Comanda --> "Gestor Comandes" : return
    deactivate Comanda

    "Gestor Comandes" --> "Interfície Comandes" : ConfirmacioIPresentarFactura()
    deactivate "Gestor Comandes"
    
    "Interfície Comandes" --> Comprador : MostrarFactura()
end

deactivate "Interfície Comandes"

@enduml
