@startuml
left to right direction
skinparam actorStyle stickman

actor "Usuari registrat" as UR
actor "Repartidor" as Repartidor

Repartidor -up-|> UR

actor "Google Maps" <<Sistema Extern>> as Gmaps

usecase "Consultar ruta de lliurament" as UC_Ruta
usecase "Acceptar repartiment" as UC_Acceptar
usecase "Consultar Comandes Pendents" as UC_ConsComandes
usecase "Actualitzar estat de la comanda" as UC_Estat

Repartidor --> UC_ConsComandes
Repartidor --> UC_Estat
Repartidor --> UC_Ruta


UC_Acceptar ..> UC_ConsComandes : <<extend>>


UC_Ruta --> Gmaps
UC_ConsComandes --> Gmaps

@enduml
